### ISSUE TITLE
CHANGES file missing in the sanction-0.4.tar.gz

### ISSUE THREAD

**Issue by pgolec** [demianbrecht/sanction#8]
Causes error when installing using pip (and presumably directly, using setup.py).

```
pip install sanction
Downloading/unpacking sanction
  Downloading sanction-0.4.tar.gz
  Running setup.py egg_info for package sanction
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/pgolec/Work/Python/sandbox/build/sanction/setup.py", line 6, in <module>
        README = README + open(os.path.join(here, "CHANGES")).read()
    IOError: [Errno 2] No such file or directory: '/Users/pgolec/Work/Python/sandbox/build/sanction/CHANGES'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/pgolec/Work/Python/sandbox/build/sanction/setup.py", line 6, in <module>

    README = README + open(os.path.join(here, "CHANGES")).read()

IOError: [Errno 2] No such file or directory: '/Users/pgolec/Work/Python/sandbox/build/sanction/CHANGES'

```

The quick 'n' dirty workaround that worked for me was to manually create that file

**Comment by fitoria** [comment]
I confirm this bug.

**Comment by demianbrecht** [comment]
Oops, sorry 'bout that. I've updated the manifest and have uploaded the changes to PyPI. Please let me know if this fixes the issue for you.

**Comment by fitoria** [comment]
It works! Thanks.

**Comment by pgolec** [comment]
Works for me, too! Thanks for the super quick fix.

**Comment by demianbrecht** [comment]
No worries, thanks for reporting it.
